# Top-level configuration
name = "my-worker"
main = "index.html"
compatibility_date = "2022-07-12"

workers_dev = false
route = { pattern = "secretstephen.com/*", zone_name = "secretstephen.com" }
